In [1]:
# Keiana Dunn
# Neural Network - FeedingForward
# Data Analysis 
# 3/1/19
# Week 7 Objective: Create code takes 5 feature values and computes two targets based 
# on random values for all weights  and biases and gives the user the option of choosing 
# either a RELU or a sigmoid function. Computation of the targets is in its own Python 
# function and accept the five features and all weights and biases as input and are output 
# the targets



In [6]:
# Import package
import numpy as np

In [7]:
# You should write your target function in this space
#====================================================

# Define RelU and Sigmoid activation functions

# Rectified Linear Unit (ReLU) used there is a matrix-vector product
def relu(x):
    return np.maximum(x,0)


# Calculate Sigmoid to get output values in a range of 0 to 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
 
#=====================================================

In [38]:
# Network size
N_input = 5
N_hidden1 = 4
N_hidden2 = 3
N_output = 2

np.random.seed(51)

# Weights and Bias Initialization

# Calculate the input to the hidden layer 1 by multiplying neuron weights in hidden layer 1 by neuron weights in input 
weights_in_hidden1 = np.random.randn(N_input,N_hidden1)
# Calculate bias 1 of hidden layer 1
bias1 = np.random.randn(N_hidden1,1)
print('weights_in_hidden1 shape',weights_in_hidden1.shape)
print(weights_in_hidden1)
print("=================================")
print('bias1 shape', bias1.shape)
print(bias1)
print("=================================")

# Calculate the hidden layer 1 to the hidden layer 2 by multiplying neuron weights in hidden layer 2 by neuron weights in hidden layer 1  
weights_in_hidden2 = np.random.randn(N_hidden2,N_hidden1)
print('weights_in_hidden2 shape',weights_in_hidden2.shape)
# Calculate bias 2 of hidden layer 2 
bias2 = np.random.randn(N_hidden2,1)

print(weights_in_hidden2)
print("=================================")
print('bias2 shape', bias2.shape)
print(bias2)
print("=================================")

# Calculate the hidden layer 2 to the output layer by multiplying neuron weights from output by neuron weights in hidden layer 2
weights_in_out = np.random.randn(N_output,N_hidden2)
print('weights_in_out shape',weights_in_out.shape)
# Calculate the bias to output of the network
bias_out = np.random.randn(N_output,1)
print(weights_in_out)
print("===========================")
print('bias_out shape', bias_out.shape)
print(bias_out)


weights_in_hidden1 shape (5, 4)
[[-0.29050317  0.11212805  1.25079512 -1.36088997]
 [ 0.09993288 -0.0479911  -0.35622969 -1.08855909]
 [-0.3510177   2.58839995 -0.50565079 -0.58430921]
 [-1.27309938  0.74678304 -0.55834612 -0.11080156]
 [-1.18733663 -1.00822592 -0.68986173 -0.08564259]]
bias1 shape (4, 1)
[[0.82275325]
 [0.9160238 ]
 [1.71684811]
 [0.51926009]]
weights_in_hidden2 shape (3, 4)
[[ 1.82871606  1.08241229  0.36862427  0.29450662]
 [-1.3362037  -1.0434206  -1.63699397  1.32806443]
 [ 0.41748389  0.71774469  1.00215744 -0.20452716]]
bias2 shape (3, 1)
[[-0.03291977]
 [-0.3731369 ]
 [ 0.31578775]]
weights_in_out shape (2, 3)
[[-0.30474632  0.36265652 -0.56065062]
 [-0.30137358  0.32172321  0.36036677]]
bias_out shape (2, 1)
[[-0.19546904]
 [-1.34061255]]


In [40]:
## Set up training data
## Each row is a case
## Columns 0-4 are features
## Columns 5 & 6 are targets

features_and_targets = np.array( 
                                   [ [0, 0, 0, 0, 0, 0, 1],
                                     [0, 0, 0, 0, 1, 0, 1],
                                     [0, 0, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 1, 1, 0, 1],
                                     [0, 1, 1, 1, 1, 0, 1],
                                     [1, 1, 1, 1, 0, 0, 1],
                                     [1, 1, 1, 0, 0, 0, 1],
                                     [1, 1, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 1, 0, 0, 1],
                                     [1, 0, 1, 1, 0, 0, 1],
                                     [1, 1, 0, 1, 0, 0, 1],
                                     [0, 1, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 0, 1, 0, 1],
                                     [1, 0, 1, 1, 1, 1, 0],
                                     [1, 1, 0, 1, 1, 1, 0],
                                     [1, 0, 1, 0, 1, 1, 0],
                                     [1, 0, 0, 0, 1, 1, 0],
                                     [1, 1, 0, 0, 1, 1, 0],
                                     [1, 1, 1, 0, 1, 1, 0],
                                     [1, 1, 1, 1, 1, 1, 0],
                                     [1, 0, 0, 1, 1, 1, 0]  ]
                           , dtype=float)

# shuffle our cases
np.random.shuffle(features_and_targets)

for i in range(22):
    # 22 feature observations 
    features = features_and_targets[i,0:5]
    # 22 target observations
    targets = features_and_targets[i,5:7]
    
# Perform a feedforward through the network using sigmoid and relu activtion function. The weights and biases from 
# input and hidden layers will be put through the activation functions. 
    
    sigmoid_predicted_value_layer2 = sigmoid((np.matmul(features, weights_in_hidden1))+ bias1)   
    # Applying sigmond activation function
   # hidden_layer_activation1 = sigmoid(hidden_layer_input1)
    print('sigmoid_predicted_value_layer2')
    print(sigmoid_predicted_value_layer2)
    
    relu_predicted_value_layer2 = relu((np.matmul(features, weights_in_hidden1))+ bias1)   
    print('relu_predicted_value_layer2')
    print(relu_predicted_value_layer2)

    sigmoid_predicted_value_layer3 = sigmoid((np.matmul(sigmoid_predicted_value_layer2, weights_in_hidden2))+ bias2)
    # Applying sigmond activation function
   # hidden_layer_activation2 = sigmoid(hidden_layer_input2)
    print(sigmoid_predicted_value_layer3)

    sigmoid_predicted_value_layer_output = sigmoid((np.matmul(sigmoid_predicted_value_layer3, weights_in_out))+ bias_out)
    # Applying sigmond activation function
   # output_layer_output = sigmoid(output_layer_input)
    print(sigmoid_predicted_value_layer_output)
    
    
# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights

    print('sigmoid_prediction_layer2 ')
    #print(sigmoid_prediction_layer2)
    print("===========================================================")
    print('sigmoid_prediction_layer3  ')
    #print(sigmoid_prediction_layer3)
    print("===========================================================")
    print('sigmoid_prediction_layer_output  ')
    #print(sigmoid_prediction_layer_output)
    print("===========================================================")
 
    print('   ')
    
#    print('Input hidden_layer ')
 #   print(hidden_layer_input_)
  #  print("===========================================================")
   # print('RelU Predictions')
    #print(hidden_layer_activation1_)
    #print("===========================================================")
    #print('hidden_layer_2 ')
    #print(hidden_layer_input2_)
    #print("===========================================================")
    #print('RelU Predictions' )
    #print(hidden_layer_activation2_)
    #print("===========================================================")
    #print('output_layer_input')
    #print(output_layer_input_)
    #print("===========================================================")
    #print('RelU Predictions' )
    #print(output_layer_output_)
    #print("===========================================================")    
    
    print('Observations', i+1,)
    print(' ')
    print('Feature : ',features, ' Target : ', targets)
    print('  ')

sigmoid_predicted_value_layer2
[[0.34184421 0.48167206 0.79958244 0.3489224 ]
 [0.36312738 0.50498132 0.81411254 0.37039824]
 [0.55946925 0.69439557 0.90702012 0.56717037]
 [0.27716265 0.40688981 0.7465306  0.2834784 ]]
relu_predicted_value_layer2
[[0.         0.         1.38368664 0.        ]
 [0.         0.01992593 1.4769572  0.        ]
 [0.2390083  0.82075024 2.2777815  0.27031555]
 [0.         0.         1.08019348 0.        ]]


ValueError: shapes (4,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [35]:
    # Relu activation function
    hidden_layer_input = np.matmul(features, weights_in_hidden1)+ bias1   
    # Applying relu activation function
    hidden_layer_activation1 = relu(hidden_layer_input)
    
    hidden_layer_input2 = np.matmul(hidden_layer_activation1, weights_in_hidden2)+ bias2
    # Applying relu activation function
    hidden_layer_activation2 = relu(hidden_layer_input2)

    output_layer_input = np.matmul(hidden_layer_activation2, weights_in_out)+ bias_out
    # Applying relu activation function
    output_layer_output = relu(output_layer_input)
    
# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights
    

    print('Input hidden_layer ')
    print(hidden_layer_input)
    print("===========================================================")
    print('RelU Predictions')
    print(hidden_layer_activation1)
    print("===========================================================")
    print('hidden_layer_2 ')
    print(hidden_layer_input2)
    print("===========================================================")
    print('RelU Predictions' )
    print(hidden_layer_activation2)
    print("===========================================================")
    print('output_layer_input')
    print(output_layer_input)
    print("===========================================================")
    print('RelU Predictions' )
    print(output_layer_output)
    print("===========================================================")
    print('Feature : ',features, ' Target : ', targets)

Observations 1


ValueError: shapes (5,) and (4,5) not aligned: 5 (dim 0) != 4 (dim 0)