In [ ]:
# Keiana Dunn
# Neural Network - Forward Feeding
# Data Analysis 
# Week 7
# 3/1/19

In [9]:
# Import package
import numpy as np

In [10]:
# You should write your target function in this space
#====================================================

# Define RelU and Sigmoid activation functions

# Rectified Linear Unit (ReLU) used there is a matrix-vector product
def relu(x):
    return np.maximum(x,0)


# Calculate Sigmoid to get output values in a range of 0 to 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
 
#=====================================================

In [11]:
# Network size
N_input = 5
N_hidden1 = 4
N_hidden2 = 3
N_output = 2

np.random.seed(42)

# Weights and Bias Initialization

# Calculate the input to the hidden layer 1 by multiplying neuron weights in hidden layer 1 by neuron weights in input 
weights_in_hidden1 = np.random.randn(N_input,N_hidden1)
# Calculate bias 1 of hidden layer 1
bias1 = np.random.randn(N_hidden1,1)

print(weights_in_hidden1)
print("=================================")
print(bias1)
print("=================================")
# Calculate the hidden layer 1 to the hidden layer 2 by multiplying neuron weights in hidden layer 2 by neuron weights in hidden layer 1  
weights_in_hidden2 = np.random.randn(N_hidden1,N_hidden2)
# Calculate bias 2 of hidden layer 2 
bias2 = np.random.randn(1,N_hidden2)

print(weights_in_hidden2)
print("=================================")
print(bias2)
print("=================================")
# Calculate the hidden layer 2 to the output layer by multiplying neuron weights from output by neuron weights in hidden layer 2
weights_in_out = np.random.randn(N_hidden2,N_output)
# Calculate the bias to output of the network
bias_out = np.random.randn(1,N_output)

print(weights_in_out)
print("===========================")
print(bias_out)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]]
[[ 1.46564877]
 [-0.2257763 ]
 [ 0.0675282 ]
 [-1.42474819]]
[[-0.54438272  0.11092259 -1.15099358]
 [ 0.37569802 -0.60063869 -0.29169375]
 [-0.60170661  1.85227818 -0.01349722]
 [-1.05771093  0.82254491 -1.22084365]]
[[ 0.2088636  -1.95967012 -1.32818605]]
[[ 0.19686124  0.73846658]
 [ 0.17136828 -0.11564828]
 [-0.3011037  -1.47852199]]
[[-0.71984421 -0.46063877]]


In [14]:
## Set up training data
## Each row is a case
## Columns 0-4 are features
## Columns 5 & 6 are targets

features_and_targets = np.array( 
                                   [ [0, 0, 0, 0, 0, 0, 1],
                                     [0, 0, 0, 0, 1, 0, 1],
                                     [0, 0, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 1, 1, 0, 1],
                                     [0, 1, 1, 1, 1, 0, 1],
                                     [1, 1, 1, 1, 0, 0, 1],
                                     [1, 1, 1, 0, 0, 0, 1],
                                     [1, 1, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 1, 0, 0, 1],
                                     [1, 0, 1, 1, 0, 0, 1],
                                     [1, 1, 0, 1, 0, 0, 1],
                                     [0, 1, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 0, 1, 0, 1],
                                     [1, 0, 1, 1, 1, 1, 0],
                                     [1, 1, 0, 1, 1, 1, 0],
                                     [1, 0, 1, 0, 1, 1, 0],
                                     [1, 0, 0, 0, 1, 1, 0],
                                     [1, 1, 0, 0, 1, 1, 0],
                                     [1, 1, 1, 0, 1, 1, 0],
                                     [1, 1, 1, 1, 1, 1, 0],
                                     [1, 0, 0, 1, 1, 1, 0]  ]
                           , dtype=float)

# shuffle our cases
np.random.shuffle(features_and_targets)

for i in range(22):
    # 22 feature observations 
    features = features_and_targets[i,0:5]
    # 22 target observations
    targets = features_and_targets[i,5:7]

# Perform a feedforward through the network using sigmoid and relu activtion function. The weights and biases from 
# input and hidden layers will be put through the activation functions. 
    
    hidden_layer_input1 = np.matmul(features, weights_in_hidden1)+ bias1   
    # Applying sigmond activation function
    hidden_layer_activation1 = sigmoid(hidden_layer_input1)
    
    hidden_layer_input2 = np.matmul(hidden_layer_activation1, weights_in_hidden2)+ bias2
    # Applying sigmond activation function
    hidden_layer_activation2 = sigmoid(hidden_layer_input2)

    output_layer_input = np.matmul(hidden_layer_activation2, weights_in_out)+ bias_out
    # Applying sigmond activation function
    output_layer_output = sigmoid(output_layer_input)
    
# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights

print('Input hidden_layer_1 ')
print(hidden_layer_input1)
print("===========================================================")
print('Sigmoid Predictions' )
print(hidden_layer_activation1)
print("===========================================================")
print('hidden_layer_input2 ')
print(hidden_layer_input2)
print("===========================================================")
print('Sigmoid Predictions' )
print(hidden_layer_activation2)
print("===========================================================")
print('output_layer_input ')
print(output_layer_input)
print("===========================================================")
print('Sigmoid Predictions' )
print(output_layer_output)
print("===========================================================")
print('Feature : ',features, ' Target : ', targets)

Input hidden_layer_1 
[[ 1.25873516  1.63580755  3.22913243  3.2903836 ]
 [-0.43268991 -0.05561752  1.53770736  1.59895853]
 [-0.1393854   0.23768699  1.83101187  1.89226304]
 [-1.63166179 -1.2545894   0.33873547  0.39998665]]
Sigmoid Predictions
[[0.7788083  0.83696366 0.96191598 0.96409743]
 [0.39348419 0.4860992  0.8231312  0.83187278]
 [0.46520996 0.55914357 0.86188222 0.86901335]
 [0.16360284 0.2219067  0.58388332 0.59868445]]
hidden_layer_input2 
[[-1.49918820e+00  1.98753982e-01 -3.65872189e+00]
 [-1.19788030e+00  9.26847692e-04 -2.94957251e+00]
 [-1.27208469e+00  6.73370585e-02 -3.09930085e+00]
 [-7.81390599e-01 -5.00849435e-01 -2.32000158e+00]]
Sigmoid Predictions
[[0.18254663 0.54952557 0.02511824]
 [0.23185251 0.50023171 0.04975672]
 [0.2189006  0.51682791 0.0431361 ]
 [0.31402026 0.37734107 0.08947993]]
output_layer_input 
[[-0.5972998  -0.42652374]
 [-0.60345952 -0.42084078]
 [-0.6011717  -0.42253593]
 [-0.62030424 -0.4046822 ]]
Sigmoid Predictions
[[0.3549617  0.39495673]

In [15]:
    # Relu activation function
    hidden_layer_input = np.matmul(features, weights_in_hidden1)+ bias1   
    # Applying relu activation function
    hidden_layer_activation1 = relu(hidden_layer_input)
    
    hidden_layer_input2 = np.matmul(hidden_layer_activation1, weights_in_hidden2)+ bias2
    # Applying relu activation function
    hidden_layer_activation2 = relu(hidden_layer_input2)

    output_layer_input = np.matmul(hidden_layer_activation2, weights_in_out)+ bias_out
    # Applying relu activation function
    output_layer_output = relu(output_layer_input)
    
# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights
    

print('Input hidden_layer ')
print(hidden_layer_input)
print("===========================================================")
print('RelU Predictions')
print(hidden_layer_activation1)
print("===========================================================")
print('hidden_layer_2 ')
print(hidden_layer_input2)
print("===========================================================")
print('RelU Predictions' )
print(hidden_layer_activation2)
print("===========================================================")
print('output_layer_input')
print(output_layer_input)
print("===========================================================")
print('RelU Predictions' )
print(output_layer_output)
print("===========================================================")
print('Feature : ',features, ' Target : ', targets)

Input hidden_layer 
[[ 1.25873516  1.63580755  3.22913243  3.2903836 ]
 [-0.43268991 -0.05561752  1.53770736  1.59895853]
 [-0.1393854   0.23768699  1.83101187  1.89226304]
 [-1.63166179 -1.2545894   0.33873547  0.39998665]]
RelU Predictions
[[1.25873516 1.63580755 3.22913243 3.2903836 ]
 [0.         0.         1.53770736 1.59895853]
 [0.         0.23768699 1.83101187 1.89226304]
 [0.         0.         0.33873547 0.39998665]]
hidden_layer_2 
[[-5.28506545  5.88516258 -7.31476523]
 [-2.40762101  2.20380688 -3.3010192 ]
 [-2.80503711  2.84558054 -3.73238875]
 [-0.41802603 -1.00323081 -1.82107919]]
RelU Predictions
[[0.         5.88516258 0.        ]
 [0.         2.20380688 0.        ]
 [0.         2.84558054 0.        ]
 [0.         0.         0.        ]]
output_layer_input
[[ 0.28868599 -1.14124771]
 [-0.34218161 -0.71550525]
 [-0.23220196 -0.78972527]
 [-0.71984421 -0.46063877]]
RelU Predictions
[[0.28868599 0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0