Keiana Dunn
Neural Network - Forward Feeding
Data Analysis 
Week 7
3/1/19

In [1]:
# Import package
import numpy as np

In [4]:
# You should write your target function in this space
#====================================================

# Define RelU and Sigmoid activation functions

# Rectified Linear Unit (ReLU) used there is a matrix-vector product
def relu(x):
    return np.maximum(x,0)


# Calculate Sigmoid to get output values in a range of 0 to 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
 
#=====================================================

In [5]:
# Network size
N_input = 5
N_hidden1 = 4
N_hidden2 = 3
N_output = 2

np.random.seed(42)

# Weights and Bias Initialization

# Calculate the input to the hidden layer 1 by multiplying neuron weights in hidden layer 1 by neuron weights in input 
weights_in_hidden1 = np.random.normal(N_hidden1, N_input)
# Calculate bias 1 of hidden layer 1
bias1 = np.random.normal(N_hidden1, 1)

print(weights_in_hidden1)
print(bias1)

# Calculate the hidden layer 1 to the hidden layer 2 by multiplying neuron weights in hidden layer 2 by neuron weights in hidden layer 1  
weights_in_hidden2 = np.random.normal(N_hidden2, N_hidden1)
# Calculate bias 2 of hidden layer 2 
bias2 = np.random.normal(N_hidden2, 1)

print(weights_in_hidden2)
print(bias2)

# Calculate the hidden layer 2 to the output layer by multiplying neuron weights from output by neuron weights in hidden layer 2
weights_in_out = np.random.normal(N_output, N_hidden2)
# Calculate the bias to output of the network
bias_out = np.random.normal(N_output, 1)


print(weights_in_out)
print(bias_out)



6.483570765056164
3.861735698828815
5.59075415240277
4.523029856408026
1.297539875829992
1.7658630430508195


In [9]:
## Set up training data
## Each row is a case
## Columns 0-4 are features
## Columns 5 & 6 are targets

features_and_targets = np.array( 
                                   [ [0, 0, 0, 0, 0, 0, 1],
                                     [0, 0, 0, 0, 1, 0, 1],
                                     [0, 0, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 1, 1, 0, 1],
                                     [0, 1, 1, 1, 1, 0, 1],
                                     [1, 1, 1, 1, 0, 0, 1],
                                     [1, 1, 1, 0, 0, 0, 1],
                                     [1, 1, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 1, 0, 0, 1],
                                     [1, 0, 1, 1, 0, 0, 1],
                                     [1, 1, 0, 1, 0, 0, 1],
                                     [0, 1, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 0, 1, 0, 1],
                                     [1, 0, 1, 1, 1, 1, 0],
                                     [1, 1, 0, 1, 1, 1, 0],
                                     [1, 0, 1, 0, 1, 1, 0],
                                     [1, 0, 0, 0, 1, 1, 0],
                                     [1, 1, 0, 0, 1, 1, 0],
                                     [1, 1, 1, 0, 1, 1, 0],
                                     [1, 1, 1, 1, 1, 1, 0],
                                     [1, 0, 0, 1, 1, 1, 0]  ]
                           , dtype=float)

# shuffle our cases
np.random.shuffle(features_and_targets)

for i in range(22):
    # 22 feature observations 
    features = features_and_targets[i,0:5]
    # 22 target observations
    targets = features_and_targets[i,5:7]

# Perform a feedforward through the network using sigmoid and relu activtion function. The weights and biases from 
# input and hidden layers will be put through the activation functions. 
    
    hidden_layer_input1 = np.dot(features, weights_in_hidden1)+ bias1   
    # Applying sigmond activation function
    hidden_layer_activation1 = sigmoid(hidden_layer_input1)
    
    hidden_layer_input2 = np.dot(hidden_layer_activation1, weights_in_hidden2)+ bias2
    # Applying sigmond activation function
    hidden_layer_activation2 = sigmoid(hidden_layer_input2)

    output_layer_in = np.dot(hidden_layer_activation2, weights_in_out)+ bias_out
    output_layer_out = sigmoid(output_layer_in)    
    
# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights
    

print('Input hidden_layer_1 ')
print(hidden_layer_input1)
print("===========================================================")
print('hidden_layer_activation1')
print(hidden_layer_activation1)
print("===========================================================")
print('Input hidden_layer_2 ')
print(hidden_layer_input2)
print("===========================================================")
print('hidden_layer_activation2')
print(hidden_layer_activation2)
print("===========================================================")
print('output_layer_in')
print(output_layer_out)
print("===========================================================")
print('Features : ',features, ' Targets : ', targets)

Input hidden_layer_1 
[10.34530646  3.8617357   3.8617357   3.8617357  10.34530646]
hidden_layer_activation1
[0.99996786 0.97940175 0.97940175 0.97940175 0.99996786]
Input hidden_layer_2 
[10.11360431  9.99862425  9.99862425  9.99862425 10.11360431]
hidden_layer_activation2
[0.99995948 0.99995454 0.99995454 0.99995454 0.99995948]
output_layer_in
[0.95535541 0.95535514 0.95535514 0.95535514 0.95535541]
Features :  [1. 0. 0. 0. 1.]  Targets :  [1. 0.]


In [ ]:
print('Feature : ',features, ' Target : ', targets)