In [1]:
# Keiana Dunn
# Neural Network - FeedingForward
# Data Analysis 
# 3/1/19
# Week 7 Objective: Create code takes 5 feature values and computes two targets based 
# on random values for all weights  and biases and gives the user the option of choosing 
# either a RELU or a sigmoid function. Computation of the targets is in its own Python 
# function and accept the five features and all weights and biases as input and are output 
# the targets



In [6]:
# Import package
import numpy as np

In [7]:
# You should write your target function in this space
#====================================================

# Define RelU and Sigmoid activation functions

# Rectified Linear Unit (ReLU) used there is a matrix-vector product
def relu(x):
    return np.maximum(x,0)


# Calculate Sigmoid to get output values in a range of 0 to 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
 
#=====================================================

In [51]:
# Network size
N_input = 5
N_hidden1 = 4
N_hidden2 = 3
N_output = 2

np.random.seed(51)

# Weights and Bias Initialization

# Calculate the input to the hidden layer 1 by multiplying neuron weights in hidden layer 1 by neuron weights in input 
weights_in_hidden1 = np.random.randn(N_input,N_hidden1)
# Calculate bias 1 of hidden layer 1
bias1 = np.random.randn(N_hidden1,1)
print('weights_in_hidden1 shape',weights_in_hidden1.shape)
print(weights_in_hidden1)
print("=================================")
print('bias1 shape', bias1.shape)
print(bias1)
print("=================================")

# Calculate the hidden layer 1 to the hidden layer 2 by multiplying neuron weights in hidden layer 2 by neuron weights in hidden layer 1  
weights_in_hidden2 = np.random.randn(N_hidden1,N_hidden2)
print('weights_in_hidden2 shape',weights_in_hidden2.shape)
# Calculate bias 2 of hidden layer 2 
bias2 = np.random.randn(N_hidden2,1)

print(weights_in_hidden2)
print("=================================")
print('bias2 shape', bias2.shape)
print(bias2)
print("=================================")

# Calculate the hidden layer 2 to the output layer by multiplying neuron weights from output by neuron weights in hidden layer 2
weights_in_out = np.random.randn(N_hidden2,N_output)
print('weights_in_out shape',weights_in_out.shape)
# Calculate the bias to output of the network
bias_out = np.random.randn(N_output,1)
print(weights_in_out)
print("===========================")
print('bias_out shape', bias_out.shape)
print(bias_out)


weights_in_hidden1 shape (5, 4)
[[-0.29050317  0.11212805  1.25079512 -1.36088997]
 [ 0.09993288 -0.0479911  -0.35622969 -1.08855909]
 [-0.3510177   2.58839995 -0.50565079 -0.58430921]
 [-1.27309938  0.74678304 -0.55834612 -0.11080156]
 [-1.18733663 -1.00822592 -0.68986173 -0.08564259]]
bias1 shape (4, 1)
[[0.82275325]
 [0.9160238 ]
 [1.71684811]
 [0.51926009]]
weights_in_hidden2 shape (4, 3)
[[ 1.82871606  1.08241229  0.36862427]
 [ 0.29450662 -1.3362037  -1.0434206 ]
 [-1.63699397  1.32806443  0.41748389]
 [ 0.71774469  1.00215744 -0.20452716]]
bias2 shape (3, 1)
[[-0.03291977]
 [-0.3731369 ]
 [ 0.31578775]]
weights_in_out shape (3, 2)
[[-0.30474632  0.36265652]
 [-0.56065062 -0.30137358]
 [ 0.32172321  0.36036677]]
bias_out shape (2, 1)
[[-0.19546904]
 [-1.34061255]]


In [66]:
## Set up training data
## Each row is a case
## Columns 0-4 are features
## Columns 5 & 6 are targets

features_and_targets = np.array( 
                                   [ [0, 0, 0, 0, 0, 0, 1],
                                     [0, 0, 0, 0, 1, 0, 1],
                                     [0, 0, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 1, 1, 0, 1],
                                     [0, 1, 1, 1, 1, 0, 1],
                                     [1, 1, 1, 1, 0, 0, 1],
                                     [1, 1, 1, 0, 0, 0, 1],
                                     [1, 1, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 1, 0, 0, 1],
                                     [1, 0, 1, 1, 0, 0, 1],
                                     [1, 1, 0, 1, 0, 0, 1],
                                     [0, 1, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 0, 1, 0, 1],
                                     [1, 0, 1, 1, 1, 1, 0],
                                     [1, 1, 0, 1, 1, 1, 0],
                                     [1, 0, 1, 0, 1, 1, 0],
                                     [1, 0, 0, 0, 1, 1, 0],
                                     [1, 1, 0, 0, 1, 1, 0],
                                     [1, 1, 1, 0, 1, 1, 0],
                                     [1, 1, 1, 1, 1, 1, 0],
                                     [1, 0, 0, 1, 1, 1, 0]  ]
                           , dtype=float)

# shuffle our cases
np.random.shuffle(features_and_targets)

for i in range(22):
    # 22 feature observations 
    features = features_and_targets[i,0:5]
    # 22 target observations
    targets = features_and_targets[i,5:7]
    
# Perform a feedforward through the network using sigmoid and relu activtion function. The weights and biases from 
# input and hidden layers will be put through the activation functions. 
    
    neuron_value_layer2S = sigmoid((np.matmul(features, weights_in_hidden1))+ bias1.T)   
    #print('neuron_value_layer2S shape', neuron_value_layer2.shape)
    print('neuron_value_layer2S')
    print(neuron_value_layer2S)
    print('  ')
    neuron_value_layer2R = relu((np.matmul(features, weights_in_hidden1))+ bias1.T)   
    #print('neuron_value_layer2R shape', neuron_value_layer2R.shape)
    print('neuron_value_layer2R')
    print(neuron_value_layer2R)
    print('  ')
    neuron_value_layer3S = sigmoid((np.matmul(neuron_value_layer2S, weights_in_hidden2))+ bias2.T)
    print('neuron_value_layer3S')
    print(neuron_value_layer3S)
    print('  ')
    neuron_value_layer3R = relu((np.matmul(neuron_value_layer2R, weights_in_hidden2))+ bias2.T)
    print('neuron_value_layer3R')
    print(neuron_value_layer3R)
    print('  ')
    neuron_value_layer_outputS = sigmoid((np.matmul(neuron_value_layer3S, weights_in_out))+ bias_out.T)
    print('neuron_value_layer_outputS')
    print(neuron_value_layer_outputS)
    print('  ')
    neuron_value_layer_outputR = relu((np.matmul(neuron_value_layer3R, weights_in_out))+ bias_out.T)
    print('neuron_value_layer_outputR')
    print(neuron_value_layer_outputR)
    print('  ')  
    print('  ')  
# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights
    print('Observations', i+1,)
    print(' ')
    print(' ')
    print('Feature : ',features, ' Target : ', targets)
    #Sigmoid_predictions = net.feedforward(features)
    #Relu_predictions = net.forwardfeed(feature)
    print('  ')  
    

neuron_value_layer2S
[[0.12039442 0.96242007 0.49074842 0.43499667]]
  
neuron_value_layer2R
[[0.         3.24298088 0.         0.        ]]
  
neuron_value_layer3S
[[0.49488789 0.39147196 0.37095316]]
  
neuron_value_layer3R
[[0.92215958 0.         0.        ]]
  
neuron_value_layer_outputS
[[0.3902125  0.24132327]]
  
neuron_value_layer_outputR
[[0. 0.]]
  
  
Observations 1
 
 
Feature :  [0. 0. 1. 1. 1.]  Target :  [0. 1.]
  
neuron_value_layer2S
[[0.36466955 0.49298417 0.87231138 0.11755071]]
  
neuron_value_layer2R
[[0.         0.         1.92155181 0.        ]]
  
neuron_value_layer3S
[[0.36251782 0.65456099 0.5685549 ]]
  
neuron_value_layer3R
[[0.         2.17880771 1.11800469]]
  
neuron_value_layer_outputS
[[0.37989175 0.23120454]]
  
neuron_value_layer_outputR
[[0. 0.]]
  
  
Observations 2
 
 
Feature :  [1. 1. 0. 0. 1.]  Target :  [1. 0.]
  
neuron_value_layer2S
[[0.27053022 0.98681423 0.8245403  0.06752782]]
  
neuron_value_layer2R
[[0.         4.31534374 1.54741664 0.  