In [1]:
# Keiana Dunn
# Neural Network - FeedingForward
# Data Analysis 
# 3/1/19
# Week 7 Objective: Code takes 5 feature values and computes two targets based 
# on random values for all weights  and biases and gives the user the option of choosing 
# either a RELU or a sigmoid function. Computation of the targets is in its own Python 
# function and accept the five features and all weights and biases as input and are output 
# the targets



In [2]:
# Import package
import numpy as np

In [3]:
# You should write your target function in this space
#====================================================

# Define RelU and Sigmoid activation functions

# Rectified Linear Unit (ReLU) used there is a matrix-vector product
def relu(x):
    return np.maximum(x,0)


# Calculate Sigmoid to get output values in a range of 0 to 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
 
#=====================================================

In [4]:
# Network size
N_input = 5
N_hidden1 = 4
N_hidden2 = 3
N_output = 2

np.random.seed(42)

# Weights and Bias Initialization

# Calculate the input to the hidden layer 1 by multiplying neuron weights in hidden layer 1 by neuron weights in input 
weights_in_hidden1 = np.random.randn(N_input,N_hidden1)
# Calculate bias 1 of hidden layer 1
bias1 = np.random.randn(N_hidden1,1)

print(weights_in_hidden1)
print("=================================")
print(bias1)
print("=================================")
# Calculate the hidden layer 1 to the hidden layer 2 by multiplying neuron weights in hidden layer 2 by neuron weights in hidden layer 1  
weights_in_hidden2 = np.random.randn(N_hidden1,N_hidden2)
# Calculate bias 2 of hidden layer 2 
bias2 = np.random.randn(N_hidden2,1)

print(weights_in_hidden2)
print("=================================")
print(bias2)
print("=================================")
# Calculate the hidden layer 2 to the output layer by multiplying neuron weights from output by neuron weights in hidden layer 2
weights_in_out = np.random.randn(N_hidden2,N_output)
# Calculate the bias to output of the network
bias_out = np.random.randn(N_output,1)

print(weights_in_out)
print("===========================")
print(bias_out)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]]
[[ 1.46564877]
 [-0.2257763 ]
 [ 0.0675282 ]
 [-1.42474819]]
[[-0.54438272  0.11092259 -1.15099358]
 [ 0.37569802 -0.60063869 -0.29169375]
 [-0.60170661  1.85227818 -0.01349722]
 [-1.05771093  0.82254491 -1.22084365]]
[[ 0.2088636 ]
 [-1.95967012]
 [-1.32818605]]
[[ 0.19686124  0.73846658]
 [ 0.17136828 -0.11564828]
 [-0.3011037  -1.47852199]]
[[-0.71984421]
 [-0.46063877]]


In [5]:
## Set up training data
## Each row is a case
## Columns 0-4 are features
## Columns 5 & 6 are targets

features_and_targets = np.array( 
                                   [ [0, 0, 0, 0, 0, 0, 1],
                                     [0, 0, 0, 0, 1, 0, 1],
                                     [0, 0, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 1, 1, 0, 1],
                                     [0, 1, 1, 1, 1, 0, 1],
                                     [1, 1, 1, 1, 0, 0, 1],
                                     [1, 1, 1, 0, 0, 0, 1],
                                     [1, 1, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 0, 0, 0, 1],
                                     [1, 0, 0, 1, 0, 0, 1],
                                     [1, 0, 1, 1, 0, 0, 1],
                                     [1, 1, 0, 1, 0, 0, 1],
                                     [0, 1, 0, 1, 1, 0, 1],
                                     [0, 0, 1, 0, 1, 0, 1],
                                     [1, 0, 1, 1, 1, 1, 0],
                                     [1, 1, 0, 1, 1, 1, 0],
                                     [1, 0, 1, 0, 1, 1, 0],
                                     [1, 0, 0, 0, 1, 1, 0],
                                     [1, 1, 0, 0, 1, 1, 0],
                                     [1, 1, 1, 0, 1, 1, 0],
                                     [1, 1, 1, 1, 1, 1, 0],
                                     [1, 0, 0, 1, 1, 1, 0]  ]
                           , dtype=float)

# shuffle our cases
np.random.shuffle(features_and_targets)

for i in range(22):
    # 22 feature observations 
    features = features_and_targets[i,0:5]
    # 22 target observations
    targets = features_and_targets[i,5:7]
    print('Observations', i+1,)
    print(' ')
# Perform a feedforward through the network using sigmoid and relu activtion function. The weights and biases from 
# input and hidden layers will be put through the activation functions. 
    
    sigmoid_prediction_layer2 = sigmoid((np.matmul(features, weights_in_hidden1))+ bias1)   
    # Applying sigmond activation function
   # hidden_layer_activation1 = sigmoid(hidden_layer_input1)
    print(sigmoid_prediction_layer2)

    sigmoid_prediction_layer3 = sigmoid((np.matmul(sigmoid_prediction_layer2, weights_in_hidden2))+ bias2)
    # Applying sigmond activation function
   # hidden_layer_activation2 = sigmoid(hidden_layer_input2)
    print(sigmoid_prediction_layer3)

    sigmoid_prediction_layer_output = sigmoid((np.matmul(sigmoid_prediction_layer3, weights_in_out))+ bias_out)
    # Applying sigmond activation function
   # output_layer_output = sigmoid(output_layer_input)
    print(sigmoid_prediction_layer_output)

     # Relu activation function
    #hidden_layer_input_ = np.matmul(features, weights_in_hidden1)+ bias1   
    # Applying relu activation function
  #  hidden_layer_activation1_ = relu(hidden_layer_input)
    
   # hidden_layer_input2_ = np.matmul(hidden_layer_activation1, weights_in_hidden2)+ bias2
    # Applying relu activation function
   # hidden_layer_activation2_ = relu(hidden_layer_input2)

   # output_layer_input_ = np.matmul(hidden_layer_activation2, weights_in_out)+ bias_out
    # Applying relu activation function
   # output_layer_output_ = relu(output_layer_input)
    
    
# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights

    print('sigmoid_prediction_layer2 ')
    print(sigmoid_prediction_layer2)
    print("===========================================================")
    print('sigmoid_prediction_layer3  ')
    print(sigmoid_prediction_layer3)
    print("===========================================================")
    print('sigmoid_prediction_layer_output  ')
    print(sigmoid_prediction_layer_output)
    print("===========================================================")
 
    print('   ')
    
#    print('Input hidden_layer ')
 #   print(hidden_layer_input_)
  #  print("===========================================================")
   # print('RelU Predictions')
    #print(hidden_layer_activation1_)
    #print("===========================================================")
    #print('hidden_layer_2 ')
    #print(hidden_layer_input2_)
    #print("===========================================================")
    #print('RelU Predictions' )
    #print(hidden_layer_activation2_)
    #print("===========================================================")
    #print('output_layer_input')
    #print(output_layer_input_)
    #print("===========================================================")
    #print('RelU Predictions' )
    #print(output_layer_output_)
    #print("===========================================================")    
    
    print('Feature : ',features, ' Target : ', targets)
    
    
    print('  ')

Observations 1
 
[[0.55608931 0.60089026 0.16373301 0.27395021]
 [0.18753314 0.21716761 0.03481956 0.06500377]
 [0.23634653 0.27112058 0.04614023 0.08527105]
 [0.06506493 0.07718518 0.01075993 0.02053111]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

In [22]:
    print('Observations', i+1,)
  
    # Relu activation function
    hidden_layer_input = np.matmul(features, weights_in_hidden1)+ bias1   
    # Applying relu activation function
    hidden_layer_activation1 = relu(hidden_layer_input)
    
    hidden_layer_input2 = np.matmul(hidden_layer_activation1, weights_in_hidden2)+ bias2
    # Applying relu activation function
    hidden_layer_activation2 = relu(hidden_layer_input2)

    output_layer_input = np.matmul(hidden_layer_activation2, weights_in_out)+ bias_out
    # Applying relu activation function
    output_layer_output = relu(output_layer_input)
    
# Call your target function here based on x
# to compute your target values based on random 
# value and biases then you can add
# your predicted y's to the print statements for all weights
    

    print('Input hidden_layer ')
    print(hidden_layer_input)
    print("===========================================================")
    print('RelU Predictions')
    print(hidden_layer_activation1)
    print("===========================================================")
    print('hidden_layer_2 ')
    print(hidden_layer_input2)
    print("===========================================================")
    print('RelU Predictions' )
    print(hidden_layer_activation2)
    print("===========================================================")
    print('output_layer_input')
    print(output_layer_input)
    print("===========================================================")
    print('RelU Predictions' )
    print(output_layer_output)
    print("===========================================================")
    print('Feature : ',features, ' Target : ', targets)

Observations 22
Input hidden_layer 
[[ 0.72201969  0.2709116  -0.98302229  0.54835764]
 [-0.96940538 -1.42051347 -2.67444736 -1.14306743]
 [-0.67610088 -1.12720896 -2.38114286 -0.84976292]
 [-2.16837727 -2.61948536 -3.87341925 -2.34203931]]
RelU Predictions
[[0.72201969 0.2709116  0.         0.54835764]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
hidden_layer_2 
[[-0.66241437 -1.59125303 -2.90770824]
 [ 0.2088636  -1.95967012 -1.32818605]
 [ 0.2088636  -1.95967012 -1.32818605]
 [ 0.2088636  -1.95967012 -1.32818605]]
RelU Predictions
[[0.        0.        0.       ]
 [0.2088636 0.        0.       ]
 [0.2088636 0.        0.       ]
 [0.2088636 0.        0.       ]]
output_layer_input
[[-0.71984421 -0.46063877]
 [-0.67872706 -0.30639999]
 [-0.67872706 -0.30639999]
 [-0.67872706 -0.30639999]]
RelU Predictions
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Feature :  [1. 0. 1. 1. 1.]  Target :  [1. 0.]
