In [ ]:
# Keiana Dunn
# Matrix Calculations
# Date: 2/27/19
# Week 3

In [1]:
# Import package
import numpy as np

In [2]:
# Matrix data

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = np.array([[6, 7], [4, 5], [8, 9]])

C = np.array([[5, 2, 7], [3, 5, 1], [7, 2, 1]])

D = np.array([[5], [8], [3]])


# Added this for looping  
result = np.array([[0,0,0], 
                   [0,0,0], 
                  [0,0,0]])

#Compute the following:

#A+C

#A-C

#AC

#CD



In [3]:
# To add A and C matrices neeed to use np.add. Both must be 3 x 3 matrices to add. 
np.add(A,C)

array([[ 6,  4, 10],
       [ 7, 10,  7],
       [14, 10, 10]])

In [4]:
# Practice making a nestloop to adds A and C matrices together. np.add is NOT needed. 
# interate through the rows
for i in range(len(A)):
    # interate through the columns
    for j in range(len(C[0])):
        result[i][j]= A[i][j] + C[i][j] 
# Elements from A and C matrices were added together and stored in result        
for r in result:
    print(r)
        

[ 6  4 10]
[ 7 10  7]
[14 10 10]


In [5]:
# Check to see what type of object was created
type(result)

numpy.ndarray

In [6]:
# To subtract A and C matrices need to use np.subtract. Both must be 3 x3 or the same structure matrix to subtract.
np.subtract(A,C)

array([[-4,  0, -4],
       [ 1,  0,  5],
       [ 0,  6,  8]])

In [7]:
# Loop practice and to check math.  np.subtract was NOT needed
# interate through rows
for i in range(len(A)):
    # interate through the columns
    for j in range(len(C)):
        result[i][j]= A[i][j]- C[i][j]
        
# The difference of elements in A and C stored in result
for r in result:
    print(r)

[-4  0 -4]
[1 0 5]
[0 6 8]


In [8]:
type(r)

numpy.ndarray

In [9]:
# To multiply A and C matrices need to use np.matmul. Two 3 x 3 matrices multiplied produced a 3 x 3 product matrix. 
np.matmul(A,C)

array([[ 32,  18,  12],
       [ 77,  45,  39],
       [122,  72,  66]])

In [10]:
# Practice nest loop with multiplying 
# interate through A rows 
for i in range(len(A)):
    # interate through C columns
    for j in range(len(C[0])):
        #interate through C rows
        for k in range(len(C)):
            result[i][j]+= A[i][j]*C[i][j]
# Store product in result
for r in result:
    print(result)

[[ 11  12  59]
 [ 37  75  23]
 [147  54  35]]
[[ 11  12  59]
 [ 37  75  23]
 [147  54  35]]
[[ 11  12  59]
 [ 37  75  23]
 [147  54  35]]


Did not produce same result as matmul

In [11]:
# Second loop attempt because * only doesn't calculate correctly for multiplying 
def matmul(A,C):
    result = [] # final result
    # interate through A rows 
    for i in range(len(A)):
        
        row = [] # the new row in new matrix
    
        # interate through C columns
        for j in range(len(C[i])):
            
            product = 0 # the new element in the new row
            
            #interate through A rows
            for v in range(len(A[i])):
                 product += A[i][v] * C[v][j]
        
            row.append(product) # append sum of product into the new row

        result.append(row) # append the new row into the final result
    return result
print(result)

[[ 11  12  59]
 [ 37  75  23]
 [147  54  35]]


Second attempt did not produce same result as matmul

In [12]:
# To multiply C and D matrices need to use np.matmul. Multiplying 3 x 3 and 3 x 1 matrices produces a 3 x 1 matrix
np.matmul(C,D)

array([[62],
       [58],
       [54]])